name: Build test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check links with linkcheck
      uses: filiph/linkcheck@2.0.23

