name: Build test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Hyperlink link checker
      uses: untitaker/hyperlink@0.1.21
      with:
        args: ./

